version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:erbium

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Save NPM cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/project
          paths: .

  typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run type checker
          command: npm run typecheck

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run linter
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: npm run test -- --ci --coverage --runInBand
      - store_artifacts:
          path: coverage

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build app
          command: npm run build
          environment:
            PUBLIC_URL: '.'
            REACT_APP_USE_HASH_ROUTER: 'true'
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  deploy:
    working_directory: ~/project/infrastructure
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Terraform
          command: |
            curl -O https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
            unzip terraform_0.11.10_linux_amd64.zip
      - run:
          name: Initialize Terraform
          command: ./terraform init
      - run:
          name: Create Terraform plan
          command: ./terraform plan --out terraform.plan
      - run:
          name: Apply Terraform plan
          command: ./terraform apply --auto-approve terraform.plan
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Sync S3 bucket
          command:
            aws s3 sync ../build s3://$(./terraform output bucket_name) --delete --metadata-directive REPLACE
            --cache-control no-cache,no-store,max-age=0
      - run:
          name: Output website endpoint
          command: ./terraform output website_endpoint

workflows:
  version: 2
  install-test-and-build:
    jobs:
      - install
      - typecheck:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - approve-deploy:
          type: approval
          requires:
            - typecheck
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - approve-deploy
